# LeeesExploitFixer 3.1.4 RELEASE
# There is no support for this plugin
# other than what is provided on the github

#Messages to send the player when they try to place illegal blocks
IllegalBlock-Place:
  Enabled: true
  Bedrock: '&6[&18b&98t&6]&6 &6That block is not allowed'
  Barrier: '&6[&18b&98t&6]&6 &6That block is not allowed'
  End_Portal_Frame: '&6[&18b&98t&6]&6 &6That block is not allowed'
  Mob_Spawner: '&6[&18b&98t&6]&6 &6That block is not allowed'


#ChunkBan skull limit tile entity limit and prevent message
ChunkBan:
  Enabled: true
  Prevent-Message: '&6[&18b&98t&6]&6 &6ChunkBan has been disabled due to an exploit (^:'
  TileEntity-Max: 500
  Skull-Max: 100


#Nether top and bottom layers
Nether:
  Enabled: true
  Top-Layer: 127
  Top-message: '&6[&18b&98t&6]&6 &6The nether top has been disabled due to lag'
  Bottom-Layer: 0
  Bottom-message: '&6[&18b&98t&6]&6 &6The nether bottom has been disabled due to lag'
  top-bottom-do-damage: true


#Message to send to the server when a player first joins
#Use {Player} as a place holder for the players name
FirstJoin:
  Enabled: true
  Message: '&6[&18b&98t&6] &c{Player}&6 has joined &18b&98t &6for the first time'


#Elytra/redstone disable TPS values keep in mind this is a double so it can be like 13.2255
#Set 0 to disable 
Elytra:
  #the speed limit is 3 by default u can change it to what you want
  SpeedLimit: 4
  #enable / disable damage when going over the speed limit
  EnableDamage: true
  #change the amount of damage taken when going over the speed limit
  DamageAmount: 15
  #the tps that elytras gets completely disabled at
  #you can turn this off by setting it to 1 basically
  Disable-TPS: 15
  #disable elytra fall damage ? set to false to enable fall damage when landing
  EnableNoFallDamage: true
  #enable taking off elytras when people go over the speed limit set to false to disable
  EnableTakingOffElytra: false
  #the message it sends to a player when they reach the elytra speed limit
  SpeedLimitReached-message: "&6[&18b&98t&6]&6 You are going to fast slow down"
  #the message it sends to opped players when a player reaches the elytra speed limit
  #you can turn this on or off by setting it to true or false
  EnableOpMessages: true
  SpeeedLimitReached-ops: "&6[&18b&98t&6]&6 Player {name} is going to fast with an elytra"
  #This will patch future clients packet elytra fly witch can be used to bypass most elytra speed limit plugins and make the elytra not lose any durability
  PacketElytraFly-Enabled: true
  #Sends a message to the player when they try to use PacketElytraFly
  SendMessage: true
  Message: "&6[&18b&98t&6]&6&6 PacketElytraFly is currently disabled due to it causing tons of lag"


#TPS to disable redstone at
Redstone:
  Disable-TPS: 15


#Misc config shit
#Message to send when a player tries to use a 32k or strength 255
IllegalDamage:
  Message: "&6[&18b&98t&6]&6&6 How did you even get a 32k out to begin with"


#Player attempts to use or drink an illegal potion or use an illegal tipped arrow
IllegalPotion:
  Message: "&6[&18b&98t&6]&6&6 Sorry those are patched"


#Message to send the player when they use an elytra in low tps use {tps} to get the elytra disable tps
ElytraLowTPS:
  Message: "&6[&18b&98t&6]&6 &6Elytras are disabled if the tps is below&r&c {tps}"


UnbookBan:
  Message: "&6[&18b&98t&6]&6&6 You have been unbookbanned"


#Message for /discord use & for colors
#make sure to add the permission l2x9core.command.discord
Discord: "&6[&18b&98t&6] Join us on discord at &chttp://discord.8b8t.me"


#Ammount of vehicles allowed in a chunk
Minecart-per-chunk:
  limit: 20


#TP on an entity exploit prevent message
tp.prevent:
  message: "&6[&18b&98t&6]&6 &6Patched"


#World name for the /world command and the fortress dat deleter
World-name: "0b0t"


#This will delete .dat files that cause memory issues every time the server shuts down
DeleteFortressDat: true


#AntiIllegal check toggles
#Only enable ChunkLoad of you have a massive problem with illegals on your server
Antiillegal:
  Block-Place-Enabled: true
  ChunkLoad-Enabled: false
  HopperTransfer-Enabled: true
  InventoryClose-Enabled: true
  InventoryOpen-Enabled: true
  PlayerHotbarMove-Enabled: true
  ItemPickup: true
  Delete-Stacked-Items: true
  Check-Illegal-Damage: true
  Illegal-Items-List:
    - "BEDROCK"
    - "COMMAND_REPEATING"
    - "COMMAND_MINECART"
    - "COMMAND_CHAIN"
    - "COMMAND"
    - "ENDER_PORTAL_FRAME"
    - "KNOWLEDGE_BOOK"
    - "MOB_SPAWNER"
    - "PORTAL"
    - "STRUCTURE_BLOCK"
    - "STRUCTURE_VOID"


#Help menu use & for colors
Help:
  #Enable the help menu from LEF
  Enabled: true
  List:
    - '&1--------------------------------------'
    - '&6Visit &chttps://www.8b8t.me &6to read the rules'
    - '&c/tpa &6to teleport to another player'
    - '&c/sethome &6to set a home at your location'
    - '&c/delhome &6to delete a home you set'
    - '&c/home &6to teleport to a home you set'
    - '&c/skin set &6to set your skin'
    - '&c/nc &6to set name color (donator1 or higher) only'
    - '&c/nick &6set a nickname (donator2 or higher) only'
    - '&c/vote &6to vote for 8b8t'
    - '&c/discord &6get an invite to the 8b8t discord'
    - '&c/kill &6to kill your self'
    - '&c/ignore &6to ignore other players'
    - '&c/msg &6to message other players'
    - '&c/changepass &6To change your password'
    - '&c/worldstats &6view the servers size'
    - '&6Visit &chttps://donate.8b8t.me &6to donate'
    - '&1--------------------------------------'


#Formatting for the say command use {message} as a place holder for the message use & for colours
#Colour codes also work in the message
SayCommandFormat: "&6[&18b&98t&6]&6 {message}"


#water / lava flowing disable tps this is useful on new servers with lots of block physics updates that cause lag
#Set -1 to disable
BlockPhysics-disable-tps: -1


#This is to prevent people from crashing / lagging the server by spam opening chest and other containers
ChestLagFix:
  MaxOpensPerSecond: 5
  KickMessage: "&6[&18b&98t&6]&6&c [AntiChestLag]&r&6 You have lost connection to the server"
  RemoveUnicodeBooks: true


#These are the connection messages for when a player joins / leaves
#Use & for colours and %player% as a placeholder for the players name
Connection:
  Player-Join-Message: ""
  Player-Leave-Message: ""


#Max amount of any entity listed here per chunk
#The formatting for this is <entity>:<amount> (i.e pig:20)
#A list of all valid entities can be found here https://helpch.at/docs/1.12.2/org/bukkit/entity/EntityType.html
EntityAmounts:
  EntityAmounts-Enabled: true
  TypePairs:
    - "ender_crystal:20"
    - "armor_stand:15"
    - "wither:30"
    - "falling_block:50"
    - "primed_tnt:5"
    - "dropped_item:50"


#Deop opped players when they leave
DeopOnLeave: true